version: 'build-{build}'

image:
  - Visual Studio 2017
  - Ubuntu1804

environment:
  matrix:
    - CMAKE_BUILD_DIR: build_auto_client
      CMAKE_OPTIONS:
      VGUI2_BUILD: 0
      SERVER_BUILD: 0
      AMXX_BUILD: 0
      
    - CMAKE_BUILD_DIR: build_auto_client_vgui2
      CMAKE_OPTIONS: -DUSE_VGUI2=1
      VGUI2_BUILD: 1
      SERVER_BUILD: 0
      AMXX_BUILD: 0
      
    - CMAKE_BUILD_DIR: build_auto_server
      CMAKE_OPTIONS:
      VGUI2_BUILD: 0
      SERVER_BUILD: 1
      AMXX_BUILD: 0
      
    - CMAKE_BUILD_DIR: build_auto_amxx
      CMAKE_OPTIONS:
      VGUI2_BUILD: 0
      SERVER_BUILD: 0
      AMXX_BUILD: 1

install:
  - sh: sudo dpkg --add-architecture i386
  - sh: sudo apt-get update > /dev/null
  - sh: sudo apt-get install -y libc6:i386 cmake gcc g++ gcc-multilib g++-multilib patchelf > /dev/null

build_script:
  - cmd: scripts/AppVeyor_WindowsBuild.bat
  - sh: |
      if [ "$SERVER_BUILD" -eq "0" ]; then
        if [ "$VGUI2_BUILD" -eq "0" ]; then
          ./scripts/MakeClientRelease.sh
        else
          ./scripts/MakeClientVGUI2Release.sh
        fi
      else
        ./scripts/MakeServerRelease.sh
      fi

artifacts:
  - path: BugfixedHL-*.zip
  - path: BugfixedHL-*.tar.gz
