version: 'build-{build}'

image:
  - Visual Studio 2017
  - Ubuntu1804

environment:
  matrix:
    - CMAKE_BUILD_DIR: build_auto_client
      CMAKE_OPTIONS:
      VGUI2_BUILD: 0
      SERVER_BUILD: 0
      
    - CMAKE_BUILD_DIR: build_auto_client_vgui2
      CMAKE_OPTIONS: -DUSE_VGUI2=1
      VGUI2_BUILD: 1
      SERVER_BUILD: 0
      
    - CMAKE_BUILD_DIR: build_auto_server
      CMAKE_OPTIONS:
      VGUI2_BUILD: 0
      SERVER_BUILD: 1

install:
  - sh: sudo dpkg --add-architecture i386
  - sh: sudo apt-get update > /dev/null
  - sh: sudo apt-get install -y libc6:i386 cmake gcc g++ gcc-multilib g++-multilib patchelf > /dev/null

build_script:
  - cmd: |
      mkdir "%CMAKE_BUILD_DIR%"
      cd "%CMAKE_BUILD_DIR%"
      cmake -DAUTO_DEPLOY=0 %CMAKE_OPTIONS% ..
      IF "%SERVER_BUILD%"=="0" (
        MSBuild.exe BugfixedHL.sln /t:client /p:PlatformTarget=x86 /p:Configuration=Release /m
        IF "%VGUI2_BUILD%"=="1" (
          ../scripts/AppVeyor_PackageClientVGUI2.bat
        ) ELSE (
          ../scripts/AppVeyor_PackageClient.bat
        )
      ) ELSE (
        MSBuild.exe BugfixedHL.sln /t:hl /p:PlatformTarget=x86 /p:Configuration=Release /m
        ../scripts/AppVeyor_PackageServer.bat
      )
  - sh: |
      if [ "$SERVER_BUILD" -eq "0" ]; then
        if [ "$VGUI2_BUILD" -eq "0" ]; then
          ./scripts/MakeClientRelease.sh
        else
          ./scripts/MakeClientVGUI2Release.sh
        fi
      else
        ./scripts/MakeServerRelease.sh
      fi

artifacts:
  - path: BugfixedHL-*.zip
  - path: BugfixedHL-*.tar.gz