version: 'build-{build}'

image:
  - Visual Studio 2017
  - Ubuntu1804

environment:
  matrix:
    - TARGET: Client
    - TARGET: ClientVGUI2
    - TARGET: Client4554
    - TARGET: Server
    - TARGET: Amxx

matrix:
  exclude:
    - image: Ubuntu1804
      TARGET: Client4554

install:
  - sh: sudo dpkg --add-architecture i386
  - sh: sudo apt-get update > /dev/null
  - sh: sudo apt-get install -y libc6:i386 cmake gcc g++ gcc-multilib g++-multilib patchelf > /dev/null
  - sh: git submodule update --init --recursive
  - cmd: git submodule update --init --recursive

build_script:
  - ps: ./scripts/BuildRelease.ps1 -Target $env:TARGET -MakeZip

artifacts:
  - path: autobuild/BugfixedHL-*.zip
