version: 'build-{build}'

image:
  - Visual Studio 2017
  - Ubuntu1804

environment:
  matrix:
    - CMAKE_BUILD_DIR: build_auto_client
      CMAKE_OPTIONS:
      VGUI2_BUILD: 0
      SERVER_BUILD: 0
      
    - CMAKE_BUILD_DIR: build_auto_client_vgui2
      CMAKE_OPTIONS: -DUSE_VGUI2=1
      VGUI2_BUILD: 1
      SERVER_BUILD: 0
      
    - CMAKE_BUILD_DIR: build_auto_server
      CMAKE_OPTIONS:
      VGUI2_BUILD: 0
      SERVER_BUILD: 1

install:
  - sh: sudo dpkg --add-architecture i386
  - sh: sudo apt update > /dev/null
  - sh: sudo apt install -y libc6:i386 cmake gcc g++ gcc-multilib g++-multilib > /dev/null

for:
# Client for Linux
-
  matrix:
    only:
      - image: Ubuntu1804

  build_script:
    - sh: 'echo Build has started: Linux Client'
    - sh: ./scripts/MakeClientRelease.sh
    
# Server for Linux
-
  matrix:
    only:
      - image: Ubuntu1804
      - SERVER_BUILD: 1

  build_script:
    - sh: 'echo Build has started: Linux Server'
    - sh: ./scripts/MakeServerRelease.sh
  
# Client with VGUI2 for Linux
-
  matrix:
    only:
      - image: Ubuntu1804
      - VGUI2_BUILD: 1

  build_script:
    - sh: 'echo Build has started: Linux Client VGUI2'
    - sh: ./scripts/MakeClientVGUI2Release.sh

# Client for Windows
-
  matrix:
    only:
      - image: Visual Studio 2017

  build_script:
    - cmd: 'ECHO Build has started: Windows'
    - cmd: mkdir %CMAKE_BUILD_DIR%
    - cmd: cd %CMAKE_BUILD_DIR%
    - cmd: cmake -DAUTO_DEPLOY=0 %CMAKE_OPTIONS% ..
    - cmd: MSBuild.exe BugfixedHL.sln /t:client /p:PlatformTarget=x86 /p:Configuration=Release /m
    - cmd: ../scripts/AppVeyor_PackageClient.bat

# Server for Windows
-
  matrix:
    only:
      - image: Visual Studio 2017
      - SERVER_BUILD: 1

  build_script:
    - cmd: 'ECHO Build has started: Windows'
    - cmd: mkdir %CMAKE_BUILD_DIR%
    - cmd: cd %CMAKE_BUILD_DIR%
    - cmd: cmake -DAUTO_DEPLOY=0 %CMAKE_OPTIONS% ..
    - cmd: MSBuild.exe BugfixedHL.sln /t:hl /p:PlatformTarget=x86 /p:Configuration=Release /m
    - cmd: ../scripts/AppVeyor_PackageServer.bat

# Client with VGUI2 for Windows
-
  matrix:
    only:
      - image: Visual Studio 2017
      - VGUI2_BUILD: 1

  build_script:
    - cmd: 'ECHO Build has started: Windows VGUI2'
    - cmd: mkdir %CMAKE_BUILD_DIR%
    - cmd: cd %CMAKE_BUILD_DIR%
    - cmd: cmake -DAUTO_DEPLOY=0 %CMAKE_OPTIONS% ..
    - cmd: MSBuild.exe BugfixedHL.sln /t:client /p:PlatformTarget=x86 /p:Configuration=Release /m
    - cmd: ../scripts/AppVeyor_PackageClientVGUI2.bat

artifacts:
  - path: BugfixedHL-*.zip
  - path: BugfixedHL-*.tar.gz