version: 'build-{build}'

image:
  - Visual Studio 2017
  - Ubuntu1804

environment:
  matrix:
    - CMAKE_BUILD_DIR: build_client
      CMAKE_OPTIONS:
      BUILD_TYPE: 0
      
    - CMAKE_BUILD_DIR: build_client_vgui2
      CMAKE_OPTIONS: -DUSE_VGUI2=1
      BUILD_TYPE: 1
      
    - CMAKE_BUILD_DIR: build_server
      CMAKE_OPTIONS:
      BUILD_TYPE: 2
      
    - CMAKE_BUILD_DIR: build_amxx
      CMAKE_OPTIONS:
      BUILD_TYPE: 3

install:
  - sh: sudo dpkg --add-architecture i386
  - sh: sudo apt-get update > /dev/null
  - sh: sudo apt-get install -y libc6:i386 cmake gcc g++ gcc-multilib g++-multilib patchelf > /dev/null
  - sh: git submodule update --recursive
  - cmd: git submodule update --recursive

build_script:
  - cmd: scripts/AppVeyor_WindowsBuild.bat
  - sh: |
      if [ "$BUILD_TYPE" -eq "0" ]; then
        ./scripts/MakeClientRelease.sh
      elif [ "$BUILD_TYPE" -eq "1" ]; then
        ./scripts/MakeClientVGUI2Release.sh
      elif [ "$BUILD_TYPE" -eq "2" ]; then
        ./scripts/MakeServerRelease.sh
      elif [ "$BUILD_TYPE" -eq "3" ]; then
        ./scripts/MakeAmxxRelease.sh
      fi

artifacts:
  - path: BugfixedHL-*.zip
  - path: BugfixedHL-*.tar.gz
